
[ClassVersion("1.0.0.0"), FriendlyName("rsWebConfigLock")]
class RS_rsWebConfigLock : OMI_BaseResource
{
	[Key] String filter;
	[write] string pspath;
	[write] string location;
	[write] boolean locked;
	[write,ValueMap{"inclusive","exclusive"},Values{"inclusive","exclusive"}] string type;
};

